language: java
dist: bionic
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11
addons:
  apt:
    packages:
      - ant-optional
script:
  - ant jar
  - ant doc
after_succes:
  - ant test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk8
