language: java
dist: bionic
osx_image: xcode9.3
addons:
  homebrew:
    update: true
    packages:
      - ant
jobs:
  include:
    - os: osx
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
script:
  - ant jar
  - ant doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk8
