language: java
dist: bionic
osx_image: xcode11.3
jdk:
  - openjdk8
  - oraclejdk11
  - openjdk11
addons:
  apt:
    packages:
      - ant-optional
jobs:
  include:
    - dist: trusty
      jdk: oraclejdk8
    - osx_image: xcode9.3
      jdk:
        - oraclejdk8
        - openjdk8
  exclude:
    - osx_image: xcode11.3
      jdk: openjdk8
script:
  - ant jar
  - ant doc
after_succes:
  - ant test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk8
