language: java
os:
  - linux
  - osx
dist: bionic
osx_image: xcode11.3
jdk:
  - oraclejdk11
  - openjdk11
jobs:
  exclude:
    - os: osx
      jdk: openjdk11
script:
  - ant jar
  - ant doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk11
