language: java
os:
  - linux
  - osx
dist: bionic
osx_image: xcode11.3
jdk:
  - openjdk8
  - oraclejdk11
  - openjdk11
addons:
  apt:
    packages:
      - ant-optional
jobs:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3
      jdk: openjdk8
  exclude:
    - os: osx
      jdk: openjdk8
script:
  - ant jar
  - ant doc
after_succes:
  - ant test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk8
